//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenId
{
    using System.Collections.Generic;
    
    
    // // ------------------------------------------------------------------------------
    // // <auto-generated>
    // //     This code was generated by the UIFramework ScreenIdProcessor.
    // //     Changes to this file may cause incorrect behavior and will be lost if
    // //     the code is regenerated.
    // // </auto-generated>
    // // ------------------------------------------------------------------------------
    public sealed class ScreenIds
    {
        
        public const string testNameFile = "testNameFile";
        
        public static Dictionary<string,string> PathMap = new Dictionary<string,string>();
        
        public ScreenIds()
        {
            ScreenIds.PathMap.Add("testNameFile", "Assets/Resources/UI/Test/testNameFile.prefab");
        }
    }
}
